version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zapier
      POSTGRES_DB: zapier-db
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/zapier:/var/lib/postgresql/data

